# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.EmailField(default='supprot@example.com', max_length=254)),
                ('sales_department', models.EmailField(blank=True, max_length=254)),
                ('twilio_account_sid', models.CharField(default='ACbcad883c9c3e9d9913a715557dddff99', max_length=255)),
                ('twilio_auth_token', models.CharField(default='abd4d45dd57dd79b86dd51df2e2a6cd5', max_length=255)),
                ('twilio_phone_number', models.CharField(default='+15006660005', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
